description: This is your frontpage
n: 12
threshold: 0.7
sections:
  - name: "Prompt Engineering"
    tag: "prompt-eng"
    queries:
      - query: "prompt AND engineering"
      - query: "chatgpt"
    threshold: 0.7
  - name: "New Datasets"
    tag: "new-dataset"
    threshold: 0.7
    queries:
      - query: "dataset OR corpus OR database"
  - name: "Data Quality"
    tag: "data-quality"
    queries:
      - query: "label AND error"
      - query: "data AND quality"
      - query: "data AND deduplication"
      - query: "data AND leakage"
    threshold: 0.7
